import { filmType } from "../types/types";

// recuo results de la bdd de moviedb
const filmList: filmType[] = [
    {
        adult: false,
        backdrop_path: "/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
        id: 872585,
        title: "Oppenheimer",
        original_language: "en",
        original_title: "Oppenheimer",
        overview:
            'En 1942, convaincus que l\'Allemagne nazie est en train de développer une arme nucléaire, les États-Unis initient, dans le plus grand secret, le "Projet Manhattan" destiné à mettre au point la première bombe atomique de l’histoire. Pour piloter ce dispositif, le gouvernement engage J. Robert Oppenheimer, brillant physicien, qui sera bientôt surnommé "le père de la bombe atomique". C\'est dans le laboratoire ultra-secret de Los Alamos, au cœur du désert du Nouveau-Mexique, que le scientifique et son équipe mettent au point une arme révolutionnaire dont les conséquences, vertigineuses, continuent de peser sur le monde actuel…',
        poster_path: "/boAUuJBeID7VNp4L7LNMQs8mfQS.jpg",
        media_type: "movie",
        genre_ids: [18, 36],
        popularity: 1118.317,
        release_date: "2023-07-19",
        video: false,
        vote_average: 8.154,
        vote_count: 5141,
    },
    {
        adult: false,
        backdrop_path: "/kjQBrc00fB2RjHZB3PGR4w9ibpz.jpg",
        id: 670292,
        title: "The Creator",
        original_language: "en",
        original_title: "The Creator",
        overview:
            "Alors qu'une future guerre entre la race humaine et l'intelligence artificielle fait rage, l'ancien agent des forces spéciales Joshua est recruté pour traquer et tuer le Créateur, l'insaisissable architecte de l'IA avancée.",
        poster_path: "/pP1cyoXFc5Br1Sg21uORSN49yyu.jpg",
        media_type: "movie",
        genre_ids: [878, 28, 53],
        popularity: 826.093,
        release_date: "2023-09-27",
        video: false,
        vote_average: 7.129,
        vote_count: 1275,
    },
    {
        adult: false,
        backdrop_path: "/t5zCBSB5xMDKcDqe91qahCOUYVV.jpg",
        id: 507089,
        title: "Five Nights at Freddy's",
        original_language: "en",
        original_title: "Five Nights at Freddy's",
        overview:
            "Mike, jeune homme perturbé, s’occupe de sa sœur Abby, âgée de 10 ans. Il est toujours hanté par la disparition, jamais élucidée, de son petit frère, survenue il y a une dizaine d’années. Récemment licencié, il a absolument besoin de retrouver un emploi pour ne pas perdre la garde d’Abby. Il accepte donc un poste de gardien de nuit, dans un restaurant désaffecté : Freddy Fazbear’s Pizzeria. Mais Mike ne tarde pas à comprendre que les apparences y sont terriblement trompeuses. Avec l’aide de Vanessa Shelly, agent de police, il est confronté, la nuit, à des phénomènes surnaturels inexplicables et bascule dans un univers cauchemardesque...",
        poster_path: "/tEY81I7lpiHaLJa7AZ3O4vWXmJo.jpg",
        media_type: "movie",
        genre_ids: [27, 9648],
        popularity: 897.338,
        release_date: "2023-10-25",
        video: false,
        vote_average: 7.848,
        vote_count: 2640,
    },
    {
        adult: false,
        backdrop_path: "/f1AQhx6ZfGhPZFTVKgxG91PhEYc.jpg",
        id: 753342,
        title: "Napoléon",
        original_language: "en",
        original_title: "Napoleon",
        overview:
            "Fresque spectaculaire, Napoléon s'attache à l'ascension et à la chute de l'Empereur Napoléon Bonaparte. Le film retrace la conquête acharnée du pouvoir par Bonaparte à travers le prisme de ses rapports passionnels et tourmentés avec Joséphine, le grand amour de sa vie.  Auteur d'épopées mémorables, Ridley Scott évoque le génie militaire ainsi que les stratégies politiques de Napoléon, tout en mettant en scène des séquences de bataille parmi les plus impressionnantes jamais filmées.",
        poster_path: "/909JHryBRMXJeVswBUDlYWK7cQr.jpg",
        media_type: "movie",
        genre_ids: [18, 36, 10752],
        popularity: 507.455,
        release_date: "2023-11-22",
        video: false,
        vote_average: 6.443,
        vote_count: 518,
    },
    {
        adult: false,
        backdrop_path: "/9PqD3wSIjntyJDBzMNuxuKHwpUD.jpg",
        id: 1075794,
        title: "Leo",
        original_language: "en",
        original_title: "Leo",
        overview:
            "Leo, un lézard blasé de 74 ans, vit dans une salle de classe en Floride depuis des décennies, avec une tortue pour copain de terrarium. Aussi, quand il apprend qu'il n'a plus qu'une année à vivre, Leo décide de s'enfuir pour découvrir la vie en liberté. Mais les petits écoliers anxieux le retiennent, craignant notamment l'arrivée d'une méchante professeure remplaçante. La liste des choses à faire absolument par le vieux lézard pendant sa dernière année de vie va s'avérer des plus étranges, mais aussi des plus gratifiantes…",
        poster_path: "/pD6sL4vntUOXHmuvJPPZAgvyfd9.jpg",
        media_type: "movie",
        genre_ids: [16, 35, 10751],
        popularity: 1914.015,
        release_date: "2023-11-17",
        video: false,
        vote_average: 7.547,
        vote_count: 372,
    },
    {
        adult: false,
        backdrop_path: "/mRmRE4RknbL7qKALWQDz64hWKPa.jpg",
        id: 800158,
        title: "The Killer",
        original_language: "en",
        original_title: "The Killer",
        overview: "Après un désastre évité de justesse, un tueur se bat contre ses employeurs et lui-même, dans une mission punitive à travers le monde qui n'a soi-disant rien de personnel.",
        poster_path: "/8L1UfKriUAdz0uJVTpQxdEuBWe4.jpg",
        media_type: "movie",
        genre_ids: [80, 53],
        popularity: 174.308,
        release_date: "2023-10-25",
        video: false,
        vote_average: 6.643,
        vote_count: 1104,
    },
    {
        adult: false,
        backdrop_path: "/5a4JdoFwll5DRtKMe7JLuGQ9yJm.jpg",
        id: 695721,
        title: "Hunger Games : La ballade du serpent et de l'oiseau chanteur",
        original_language: "en",
        original_title: "The Hunger Games: The Ballad of Songbirds \u0026 Snakes",
        overview:
            'Préquelle de Hunger Games se déroulant 64 ans plus tôt, dans les années qui ont suivi la période des "Jours sombres", la première rébellion ratée à Panem…  De nombreuses années avant de devenir Président de Panem, le jeune Coriolanus Snow est choisi comme mentor du district 12 lors des nouveaux Hunger Games.',
        poster_path: "/rMKxQ2B54BIhc7BG8I9CmQuhsFT.jpg",
        media_type: "movie",
        genre_ids: [28, 10749, 18],
        popularity: 436.177,
        release_date: "2023-11-15",
        video: false,
        vote_average: 7.31,
        vote_count: 545,
    },
    {
        adult: false,
        backdrop_path: "/sp6egj5NHHRGmCMdIoTNdbLwACR.jpg",
        id: 1022964,
        title: "Noël à Candy Cane Lane",
        original_language: "en",
        original_title: "Candy Cane Lane",
        overview:
            "L'histoire d'un homme déterminé à gagner le concours annuel de décoration de Noël de son quartier et qui, sans le savoir, signe un pacte avec un elfe malfaisant qui donne vie aux créatures des 12 jours de Noël.",
        poster_path: "/8qfOQ7YPtvN2ATM50iUk58hZsNf.jpg",
        media_type: "movie",
        genre_ids: [35, 14, 10751],
        popularity: 137.593,
        release_date: "2023-11-29",
        video: false,
        vote_average: 6.5,
        vote_count: 54,
    },
    {
        adult: false,
        backdrop_path: "/zIYROrkHJPYB3VTiW1L9QVgaQO.jpg",
        id: 897087,
        title: "Freelance",
        original_language: "en",
        original_title: "Freelance",
        overview:
            "Un agent des forces spéciales décide de prendre sa retraite de l’armée et de fonder une famille aux États-Unis. Après plusieurs années d’efforts pour se conformer à la vie en banlieue, il décide de sortir de sa retraite et d’accepter un contrat pour assurer la sécurité d’une journaliste alors qu’elle interviewe un dictateur sud-américain. Lorsqu’un coup d’État militaire éclate en plein milieu de l’interview, les voici tous trois contraints de s‘enfuir dans la jungle où ils doivent survivre aux éléments, aux militaires et les uns aux autres.",
        poster_path: "/sUhK63JNkcnq9tfcy6jLaXgN33x.jpg",
        media_type: "movie",
        genre_ids: [28, 35],
        popularity: 287.552,
        release_date: "2023-10-05",
        video: false,
        vote_average: 6.467,
        vote_count: 121,
    },
    {
        adult: false,
        backdrop_path: "/fc2pEZgr0ltmyzLl4cO9JInOg6l.jpg",
        id: 798021,
        title: "Family Switch",
        original_language: "en",
        original_title: "Family Switch",
        overview:
            "Jess et Bill Walker s'efforcent de garder la famille soudée alors que leurs enfants s'éloignent et deviennent indépendants. Un jour, après une séance fortuite d'astrologie, les Walker se réveillent dans un corps qui n'est pas le leur, le matin même de ce qui doit être la journée la plus importante de leur vie. Parviendront-ils à se serrer les coudes pour décrocher une promotion, réussir un entretien d'entrée dans une université, signer un contrat musical et obtenir une sélection dans une équipe de football ?",
        poster_path: "/fnRUCA0fjEb3kuIaTGogL7425IC.jpg",
        media_type: "movie",
        genre_ids: [35, 14, 10751],
        popularity: 221.508,
        release_date: "2023-11-30",
        video: false,
        vote_average: 6.327,
        vote_count: 110,
    },
    {
        adult: false,
        backdrop_path: "/xgGGinKRL8xeRkaAR9RMbtyk60y.jpg",
        id: 901362,
        title: "Les Trolls 3",
        original_language: "en",
        original_title: "Trolls Band Together",
        overview:
            "Après deux films à se tourner autour pour finalement tomber dans les bras l’un de l’autre, Poppy et Branch sont officiellement en couple (#broppy)! Alors qu’ils n’ont plus de secrets l’un pour l’autre, Poppy fait une découverte incroyable relative au passé de Branch. À l’époque, avec ses quatre frères, Floyd, John Dory, Spruce et Clay, ils formaient le Boys Band le plus en vogue du moment, les BroZone. Alors qu’il n’était qu’un enfant, le groupe s’est séparé, tout comme la famille et depuis Branch n’a jamais revu ses frères.",
        poster_path: "/r5uiTUeqoERL66fNgtPVbTViHml.jpg",
        media_type: "movie",
        genre_ids: [16, 10751, 10402, 14, 35],
        popularity: 1319.467,
        release_date: "2023-10-12",
        video: false,
        vote_average: 7.262,
        vote_count: 254,
    },
    {
        adult: false,
        backdrop_path: "/35z8hWuzfFUZQaYog8E9LsXW3iI.jpg",
        id: 335977,
        title: "Indiana Jones et le Cadran de la destinée",
        original_language: "en",
        original_title: "Indiana Jones and the Dial of Destiny",
        overview:
            "1969. Après avoir passé plus de dix ans à enseigner au Hunter College de New York, l'estimé docteur Jones, professeur d'archéologie, est sur le point de prendre sa retraite et de couler des jours paisibles. Tout bascule après la visite surprise de sa filleule Helena Shaw, qui est à la recherche d'un artefact rare que son père a confié à Indy des années auparavant : le fameux cadran d'Archimède, une relique qui aurait le pouvoir de localiser les fissures temporelles. En arnaqueuse accomplie, Helena vole l’objet et quitte précipitamment le pays afin de le vendre au plus offrant. Indy n'a d'autre choix que de se lancer à sa poursuite. Il ressort son fédora et son blouson de cuir pour une dernière virée...",
        poster_path: "/1TMczPTGEtl2DrpWNEy7aLm7XxB.jpg",
        media_type: "movie",
        genre_ids: [12, 28],
        popularity: 370.322,
        release_date: "2023-06-28",
        video: false,
        vote_average: 6.68,
        vote_count: 2141,
    },
    {
        adult: false,
        backdrop_path: "/628Dep6AxEtDxjZoGP78TsOxYbK.jpg",
        id: 575264,
        title: "Mission : Impossible - Dead Reckoning Partie 1",
        original_language: "en",
        original_title: "Mission: Impossible - Dead Reckoning Part One",
        overview:
            "Ethan Hunt et son équipe de l’IMF se lancent dans leur mission la plus périlleuse à ce jour : traquer une effroyable nouvelle arme avant que celle-ci ne tombe entre de mauvaises mains et menace l’humanité entière. Le contrôle du futur et le destin du monde sont en jeu. Alors que les forces obscures de son passé ressurgissent, Ethan s’engage dans une course mortelle autour du globe. Confronté à un puissant et énigmatique ennemi, Ethan réalise que rien ne peut se placer au-dessus de sa mission - pas même la vie de ceux qu’il aime.",
        poster_path: "/nVIUNhVsG0HDwyOJihlpsSZ8SHR.jpg",
        media_type: "movie",
        genre_ids: [28, 53],
        popularity: 574.409,
        release_date: "2023-07-08",
        video: false,
        vote_average: 7.593,
        vote_count: 2611,
    },
    {
        adult: false,
        backdrop_path: "/feSiISwgEpVzR1v3zv2n2AU4ANJ.jpg",
        id: 609681,
        title: "The Marvels",
        original_language: "en",
        original_title: "The Marvels",
        overview:
            "Lorsque Carol Danvers, alias Captain Marvel, se retrouve dans un étrange vortex lié à une révolution kree, ses pouvoirs  se mêlent à ceux de Kamala Khan, alias Miss Marvel, et à ceux de sa nièce, le capitaine Monica Rambeau, désormais astronaute du S.A.B.E.R. Ce trio improbable va devoir travailler ensemble pour sauver l'univers.",
        poster_path: "/mqAQO6j5gkq6iwCXNbXpzf0RXBU.jpg",
        media_type: "movie",
        genre_ids: [878, 12, 28],
        popularity: 411.67,
        release_date: "2023-11-08",
        video: false,
        vote_average: 6.6,
        vote_count: 592,
    },
    {
        adult: false,
        backdrop_path: "/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg",
        id: 346698,
        title: "Barbie",
        original_language: "en",
        original_title: "Barbie",
        overview:
            "Parallèlement au monde réel, il existe Barbie Land, un monde parfait où les poupées Barbie vivent joyeusement, persuadées d'avoir rendu les filles humaines heureuses. Mais un jour, une Barbie commence à se poser des questions et à devenir humaine. Sur les conseils d'une Barbie étrange, elle part pour le monde réel afin de retrouver la fille à laquelle elle appartenait afin de pouvoir retrouver sa perfection. Dans sa quête, elle est accompagnée par un Ken fou amoureux d'elle qui va également trouver un sens à sa vie dans le monde réel…",
        poster_path: "/oQjqjIQ46VVa8Q80y3FfLrPXoK3.jpg",
        media_type: "movie",
        genre_ids: [35, 12, 14],
        popularity: 353.419,
        release_date: "2023-07-19",
        video: false,
        vote_average: 7.184,
        vote_count: 6112,
    },
    {
        adult: false,
        backdrop_path: "/ehumsuIBbgAe1hg343oszCLrAfI.jpg",
        id: 1022796,
        title: "Wish, Asha et la bonne étoile",
        original_language: "en",
        original_title: "Wish",
        overview:
            "Asha, jeune fille de 17 ans à l’esprit vif et dévouée à ses proches, vit à Rosas, un royaume où tous les souhaits peuvent littéralement s’exaucer. Dans un moment de désespoir, elle adresse un vœu aux étoiles auquel va répondre une force cosmique : une petite boule d’énergie infinie prénommée Star. Ensemble, Star et Asha vont affronter le plus redoutable des ennemis et prouver que le souhait d’une personne déterminée, allié à la magie des étoiles, peut produire des miracles...",
        poster_path: "/ai0Nmib9SKw21xpocmHKiUANWb.jpg",
        media_type: "movie",
        genre_ids: [16, 10751, 14, 12],
        popularity: 352.191,
        release_date: "2023-11-13",
        video: false,
        vote_average: 6.647,
        vote_count: 78,
    },
    {
        adult: false,
        backdrop_path: "/sQLMaESdeELB7Dl8HdxfGlZYRzu.jpg",
        id: 840430,
        title: "Winter Break",
        original_language: "en",
        original_title: "The Holdovers",
        overview:
            "Un instructeur maussade d'une école préparatoire de la Nouvelle-Angleterre reste sur le campus pendant les vacances de Noël pour garder une poignée d'étudiants qui n'ont nulle part où aller. Il noue bientôt un lien improbable avec un fauteur de troubles intelligent, mais endommagé, et avec la cuisinière en chef de l'école, une femme qui vient de perdre un fils pendant la guerre du Vietnam.",
        poster_path: "/uLNBKjK2MPIyHpfcS0hIP48BjHZ.jpg",
        media_type: "movie",
        genre_ids: [35, 18],
        popularity: 265.81,
        release_date: "2023-10-27",
        video: false,
        vote_average: 7.8,
        vote_count: 77,
    },
    {
        adult: false,
        backdrop_path: "/kHlX3oqdD4VGaLpB8O78M25KfdS.jpg",
        id: 945729,
        title: "Mystère à Venise",
        original_language: "en",
        original_title: "A Haunting in Venice",
        overview:
            "Après la Seconde Guerre mondiale en une sombre veille de Toussaint. Retraité, vivant un exil volontaire dans la resplendissante Venise, en Italie, Poirot assiste à contre-cœur à une séance de spiritisme dans un palazzo hanté en ruines. Quand une invitée est assassinée, le détective est propulsé dans un univers sinistre d'obscurité et de secrets.",
        poster_path: "/wQdOoevcY3cYDySvtcezd1AkP1p.jpg",
        media_type: "movie",
        genre_ids: [9648, 53, 80],
        popularity: 134.186,
        release_date: "2023-09-13",
        video: false,
        vote_average: 6.761,
        vote_count: 1363,
    },
    {
        adult: false,
        backdrop_path: "/tC78Pck2YCsUAtEdZwuHYUFYtOj.jpg",
        id: 926393,
        title: "Equalizer 3",
        original_language: "en",
        original_title: "The Equalizer 3",
        overview:
            "Depuis qu'il a renoncé à sa vie d'assassin au service du gouvernement, Robert McCall peine à enterrer les démons de son passé et trouve un étrange réconfort en défendant les opprimés. Alors qu'il pense avoir trouvé un havre de paix dans le sud de l'Italie, il découvre que ses amis sont sous le contrôle de la mafia locale. Quand les évènements prennent une tournure mortelle, McCall sait exactement ce qu'il doit faire : protéger ses amis en s'attaquant directement à la pègre.",
        poster_path: "/go2gtucO5LT92jnU40pbD0LImgg.jpg",
        media_type: "movie",
        genre_ids: [28, 53, 80],
        popularity: 466.169,
        release_date: "2023-08-30",
        video: false,
        vote_average: 7.425,
        vote_count: 1789,
    },
    {
        adult: false,
        backdrop_path: "/dZbLqRjjiiNCpTYzhzL2NMvz4J0.jpg",
        id: 951491,
        title: "Saw X",
        original_language: "en",
        original_title: "Saw X",
        overview:
            "Dans l'espoir d'une guérison miraculeuse, John Kramer se rend au Mexique pour une procédure médicale risquée et expérimentale, pour découvrir que toute l'opération est une arnaque visant à escroquer les plus vulnérables. Armé d'un nouvel objectif, le tristement célèbre tueur en série utilise des pièges dérangés et ingénieux pour renverser la situation contre les escrocs.",
        poster_path: "/u7Lp1Hi8aBS73jv4KRMIv5aK4ax.jpg",
        media_type: "movie",
        genre_ids: [27, 53],
        popularity: 396.738,
        release_date: "2023-09-26",
        video: false,
        vote_average: 7.397,
        vote_count: 1194,
    },
];

export { filmList };
